on:
  pull_request:
    branches:
      - desdeo2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create needed folders folder
        run: mkdir -p $HOME/tmp/custom_binaries

      - name: Download custom binaries
        run: wget https://github.com/industrial-optimization-group/DESDEO/releases/download/supplementary/solver_binaries.tgz -O $HOME/tmp/binaries.tgz

      - name: Extract custom binaries
        run: tar --strip-components=1 -xzf $HOME/tmp/binaries.tgz -C $HOME/tmp/custom_binaries

      - name: Make binaries executable
        run: chmod +x $HOME/tmp/custom_binaries/*

      - name: Add binaries to path
        run: echo "$HOME/tmp/custom_binaries" >> "$GITHUB_PATH"

      - name: Check path
        run: echo $PATH

      - name: Check that binaries are available
        run: |
          ipopt --version
          bonmin --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python and Pytest paths
        run: |
          which python
          which pytest
          pytest -k "not performance and not nautili and not api and not gurobipy and not skip" --collect-only

      - name: Run tests
        run: |
          pytest -k "not performance and not nautili and not api and not gurobipy and not skip and not nogithub" --disable-warnings --maxfail=5
